### ISSUE TITLE
Deploy fails

### ISSUE THREAD

**Issue by matt-chan** [theochem/cgbasis#16]
@tovrstra Have you seen this error before? 

Current tag is: 0.1.0
/home/travis/.rvm/gems/ruby-2.2.7/gems/octokit-4.6.2/lib/octokit/response/raise_error.rb:16:in `on_complete': POST https://api.github.com/repos/theochem/gbasis/releases: 404 - Not Found // See: https://developer.github.com/v3 (Octokit::NotFound)

The builds are failing. I'm pretty sure it's not an issue with the keys...

**Comment by tovrstra** [comment]
Not seen this one either.

**Comment by matt-chan** [comment]
The build log is here:

https://travis-ci.org/theochem/gbasis/jobs/275038896

**Comment by matt-chan** [comment]
Figured it out. The buildtools team wasn't given write permissions for the repo.
