### ISSUE TITLE
libint2 should be list as a dependence

### ISSUE THREAD

**Issue by tczorro** [theochem/cgbasis#17]
In file included from gbasis/gbasis.h:26:0,
                 from gbasis/cext.cpp:460:
gbasis/ints.h:26:10: fatal error: libint2.h: No such file or directory
 #include "libint2.h"

**Comment by tovrstra** [comment]
Thanks for noticing. You're right. If you look into [tools/meta.yml](../blob/master/tools/conda.recipe/meta.yaml), it is listed as a dependency. All things listed there should be mentioned in the `README.rst` file as well. Could you also replace the MardDown syntax for the badges by restructeredText?

**Comment by matt-chan** [comment]
Conda builds fix this. Users shouldn't need to build themselves anymore.
