### ISSUE TITLE
API improvement: different integral backends

### ISSUE THREAD

**Issue by tovrstra** [theochem/cgbasis#9]
We should make it possible to use different backends to compute certain integrals, e.g. [LibInt](https://github.com/evaleev/libint) and [libcint](https://github.com/sunqm/libcint)

**Comment by tovrstra** [comment]
Replaces theochem/horton#50

**Comment by PaulWAyers** [comment]
This is subsumed by https://github.com/theochem/gbasis/issues/112

We are now directly linking the Python version of gbasis with a c++ fallback through `libcint`. I'm going to close this (stale) issue therefore.
